version: "3"
services:
  app:
    image: teatarapp
    ports:
      - "8080:8080"
    networks:
      - mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=

networks:
  employee-mysql:
